// <auto-generated />
using System;
using Kurisu.RemoteCall.Attributes;
using Xunit;

namespace Kurisu.Test.RemoteCall.UnitTests
{
    public class AbstractRequestInterceptorAttribute_Tests
    {
        private class DummyInterceptor : AbstractRequestInterceptorAttribute<string>
        {
        }

        [Fact]
        public void TryOnException_Default_ReturnsFalseAndDefaultResult()
        {
            var interceptor = new DummyInterceptor();
            var ex = new Exception("before-throw");
            var handled = interceptor.TryOnException(ex, out var result);
            Assert.False(handled);
            Assert.Equal(default(string), result);
        }
    }
}

