// <auto-generated />
using Kurisu.RemoteCall.Attributes;
using Kurisu.RemoteCall.Attributes.HelpMethods;

namespace Kurisu.Test.RemoteCall.UnitTests;

public class HttpMethodAttributes_GeneratedTests
{
    [Fact]
    public void DeleteAttribute_Defaults()
    {
        var a = new DeleteAttribute();
        Assert.Equal(string.Empty, a.Template);
        Assert.Equal(System.Net.Http.HttpMethod.Delete, a.HttpMethod);

        var b = new DeleteAttribute("api/test/{id}");
        Assert.Equal("api/test/{id}", b.Template);
        Assert.Equal(System.Net.Http.HttpMethod.Delete, b.HttpMethod);
    }

    [Fact]
    public void PatchAttribute_Defaults()
    {
        var a = new PatchAttribute();
        Assert.Equal(string.Empty, a.Template);
        Assert.Equal(System.Net.Http.HttpMethod.Patch, a.HttpMethod);

        var b = new PatchAttribute("api/patch");
        Assert.Equal("api/patch", b.Template);
        Assert.Equal(System.Net.Http.HttpMethod.Patch, b.HttpMethod);
    }

    [Fact]
    public void PutAttribute_Defaults()
    {
        var a = new PutAttribute();
        Assert.Equal(string.Empty, a.Template);
        Assert.Equal(System.Net.Http.HttpMethod.Put, a.HttpMethod);

        var b = new PutAttribute("api/put");
        Assert.Equal("api/put", b.Template);
        Assert.Equal(System.Net.Http.HttpMethod.Put, b.HttpMethod);
    }
}

