// <auto-generated />
using System.Net.Http;
using Kurisu.RemoteCall.Attributes;
using Kurisu.RemoteCall.Attributes.HelpMethods;
using PostHelp = Kurisu.RemoteCall.Attributes.HelpMethods.PostAttribute;
using Xunit;

namespace Kurisu.Test.RemoteCall.UnitTests
{
    public class HttpMethodAttributes_Tests
    {
        [Fact]
        public void GetAttribute_Defaults()
        {
            var a = new GetAttribute();
            Assert.Equal(string.Empty, a.Template);
            Assert.Equal(HttpMethod.Get, a.HttpMethod);
        }

        [Fact]
        public void PostAttribute_DefaultsAndOptions()
        {
            var p = new PostHelp("api", contentType: "application/json", asUrlencodedFormat: true);
            Assert.Equal("api", p.Template);
            Assert.Equal("application/json", p.ContentType);
            Assert.True(p.AsUrlencodedFormat);

            var form = new PostHelp("api", contentType: "application/x-www-form-urlencoded");
            Assert.True(form.AsUrlencodedFormat);
        }

        [Fact]
        public void OtherAttributes_HaveCorrectHttpMethods()
        {
            Assert.Equal(HttpMethod.Put, new PutAttribute().HttpMethod);
            Assert.Equal(HttpMethod.Patch, new PatchAttribute().HttpMethod);
            Assert.Equal(HttpMethod.Delete, new DeleteAttribute().HttpMethod);
        }
    }
}
