// <auto-generated />
using System.Collections.Generic;
using Kurisu.RemoteCall.Abstractions;
using Kurisu.RemoteCall.Default;
using Kurisu.RemoteCall.Utils;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Kurisu.Test.RemoteCall.UnitTests
{
    public class RemoteCall_UrlResolver_ConfigurationInterpolation_Tests
    {
        [Fact]
        public void ResolveUrl_BaseUrlPlaceholder_IsReplacedFromConfiguration()
        {
            // Arrange
            var inMemory = new Dictionary<string, string>
            {
                ["Auth:Url"] = "http://localhost:5003"
            };

            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(inMemory)
                .Build();

            var services = new ServiceCollection();
            services.AddSingleton<IConfiguration>(configuration);
            services.AddSingleton<ICommonUtils, CommonUtils>();
            // DefaultRemoteCallUrlResolver depends on ICommonUtils; CommonUtils requires IJsonSerializer
            services.AddSingleton<IJsonSerializer, Kurisu.RemoteCall.Utils.NewtonsoftJsonSerializer>();
            services.AddSingleton<IRemoteCallUrlResolver, DefaultRemoteCallUrlResolver>();

            var sp = services.BuildServiceProvider();
            var resolver = sp.GetRequiredService<IRemoteCallUrlResolver>();

            // baseUrl contains placeholder
            var baseUrlTemplate = "${Auth:Url}";
            var template = "api/check";

            // Act
            var resolved = resolver.ResolveUrl("GET", baseUrlTemplate, template, new List<Kurisu.RemoteCall.ParameterValue>());

            // Assert
            Assert.Equal("http://localhost:5003/api/check", resolved);
        }
    }
}

