// <auto-generated />
using Kurisu.RemoteCall.Utils;
using Kurisu.RemoteCall;
using Xunit;

namespace Kurisu.Test.RemoteCall.UnitTests;

public class Utils_SimpleTests
{
    [Fact]
    public void RemoteCallStatic_DefaultClientName_GetSet()
    {
        var original = RemoteCallStatic.DefaultClientName;
        try
        {
            RemoteCallStatic.DefaultClientName = "test-client";
            Assert.Equal("test-client", RemoteCallStatic.DefaultClientName);
        }
        finally
        {
            RemoteCallStatic.DefaultClientName = original;
        }
    }

    [Fact]
    public void NewtonsoftJsonSerializer_DeserializeWithType_Works()
    {
        var serializer = new NewtonsoftJsonSerializer();
        var json = "{\"Name\":\"abc\",\"Age\":30}";
        var obj = serializer.Deserialize(json, typeof(TestModel));
        Assert.NotNull(obj);
        Assert.IsType<TestModel>(obj);
        var tm = (TestModel)obj;
        Assert.Equal("abc", tm.Name);
        Assert.Equal(30, tm.Age);
    }

    private class TestModel { public string Name { get; set; } = null!; public int Age { get; set; } }
}

