// <auto-generated />
using System;
using Kurisu.DataAccessor.Abstractions;
using Kurisu.DataAccessor.Internal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kurisu.Gateway.Migrations
{
    [DbContext(typeof(DefaultAppDbContext<IAppMasterDb>))]
    [Migration("20220724112540_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Kurisu.Gateway.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int?>("Updater")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Kurisu.Gateway.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<string>("DownstreamHttpMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("DownstreamHttpVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("DownstreamPathTemplate")
                        .HasColumnType("longtext");

                    b.Property<string>("DownstreamScheme")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Timeout")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int?>("Updater")
                        .HasColumnType("int");

                    b.Property<string>("UpstreamHttpMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("UpstreamPathTemplate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Kurisu.Gateway.Entities.RouteHostPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<string>("Host")
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int?>("Updater")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RouteHostPorts");
                });

            modelBuilder.Entity("Manon.Gateway.ApplicationCore.Entities.GlobalConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<string>("DownstreamHttpVersion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(3)");

                    b.Property<int?>("Updater")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GlobalConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
