<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.7.5</Version>
	</PropertyGroup>
	<ItemGroup>
        <ProjectReference Include="..\Kurisu.Extensions.SqlSugar\Kurisu.Extensions.SqlSugar.csproj"/>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Kurisu.AspNetCore.Abstractions\Kurisu.AspNetCore.Abstractions.csproj" />
	</ItemGroup>
</Project>