<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>ligy</Authors>
        <Version>1.1.7</Version>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
        <ProjectReference Include="..\Kurisu.Aspect.Abstractions\Kurisu.Aspect.Abstractions.csproj"/>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
	</ItemGroup>
</Project>